# Generated by Django 6.0.1 on 2026-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30, verbose_name='Fecha Evento')),
                ('hora', models.CharField(max_length=10, verbose_name='Hora Evento')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripcion')),
                ('estado', models.CharField(max_length=20, verbose_name='Esatus')),
            ],
        ),
    ]
