# Generated by Django 6.0.1 on 2026-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Usuario')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellido Usuario')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo Usuario')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave Usuario')),
            ],
        ),
    ]
